#!/bin/sh

DB_56=192.168.0.56
DB_116=192.168.0.116
DB_NAME=stonefree
DB_USER=pc8
DIR_NAME=schema

[ -d $DIR_NAME ] || mkdir $DIR_NAME
dump_56=$DIR_NAME/dump_56_`date '+%Y%m%d%H%M%S'`.sql
dump_116=$DIR_NAME/dump_116_`date '+%Y%m%d%H%M%S'`.sql

pg_dump -h $DB_56 -U $DB_USER $DB_NAME -s -f $dump_56
pg_dump -h $DB_116 -U $DB_USER $DB_NAME -s -f $dump_116

java -jar apgdiff-2.4.jar --ignore-start-with $dump_116 $dump_56 > $DIR_NAME/update_116_diff_`date '+%Y%m%d%H%M%S'`.sql
java -jar apgdiff-2.4.jar --ignore-start-with $dump_56 $dump_116 > $DIR_NAME/update_56_diff_`date '+%Y%m%d%H%M%S'`.sql

exit $?
